### ISSUE TITLE
sidebar not open

### ISSUE THREAD

**Issue by nguyentranchung** [tailwindadmin/admin#1] opened 2019-02-07 02:58 UTC
![image](https://user-images.githubusercontent.com/9611224/52387995-b680c500-2acf-11e9-9eef-41756da53dd1.png)

**Comment by riteshsingh1** [comment] 2019-02-12 04:06
Hi Can You provide more details, like broswer and maybe paste a scrrenshot?

**Comment by riteshsingh1** [comment] 2019-02-15 07:16
Unable to reproduce this issue, hence closing..

**Comment by nguyentranchung** [comment] 2019-02-15 11:43
I run it on brave browser, it worked on chrome

**Comment by riteshsingh1** [comment] 2019-04-06 06:03
Working on brave browser also, hence closing this issue.

**Closed as completed by riteshsingh1** 2019-04-06 06:03 UTC
Labels: bug
